web/app/task-manager-app/config/routes.rb
Rails.application.routes.draw do

  root 'kanbans#index'
  resources :kanbans, only: [:create, :update, :destroy]
  resources :tasks, only: [:create, :update, :destroy]
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/top', to: 'top#index'
  patch '/tasks/update/sort', to: 'tasks#update_sort'
end

web/app/task-manager-app/app/models/kanban.rb
class Kanban < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
end

web/app/task-manager-app/app/controllers/kanbans_controller.rb
class KanbansController < ApplicationController
  before_action :logged_in_user

  def index
    @kanban = Kanban.new
    @task = Task.new
    @kanbans = current_user.kanbans.includes(:tasks).order('kanbans.id').order('tasks.sort')
  end

  def create
    @kanban = current_user.kanbans.build(kanban_params)
    flash[:success] = "かんばんを作成しました" if @kanban.save
      
    redirect_to root_url
  end

  def update
    @kanban = Kanban.find(params[:id])
    if @kanban.user_id == current_user.id
      if @kanban.update_attributes(kanban_params)
        render json: {response: 'ok'}
      end
    end
  end

  def destroy
    @kanban = Kanban.find(params[:id])
    str = @kanban.name
    @kanban.destroy
    flash[:success] = "#{str}を削除しました。"
    redirect_to root_url
  end

  private

    def kanban_params
      params.require(:kanban).permit(:name)
    end
end

web/app/task-manager-app/app/helpers/kanbans_helper.rb
module KanbansHelper
end

web/app/task-manager-app/app/views/kanbans/_form.html.erb
<%= form_for(@kanban, url: kanbans_path) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field has-addons">
    <div class="control">
      <%= f.text_field :name, class: "input", placeholder: "かんばん名" %>
    </div>
    <%= f.submit "+", class: "button is-link" %>
  </div>
<% end %>

web/app/task-manager-app/app/views/kanbans/index.html.erb
<div class="container has-text-centered">
  <% if @kanbans.any? %>
    <%= render 'form'%>
    <div class="kanban-container">
      <div class="columns is-mobile is-multiline is-centered">
        <% @kanbans.each_with_index do |kanban, kanbanIndex| %>
          <div class="column is-12-touch is-4-desktop">
            <div class="card">
              <div class="card-content" data-kanban-id="<%=kanban.id%>">
                <div class="kanban-row" data-kanban-id="<%=kanban.id%>">
                  <span class="kanban-name"><%= kanban.name %></span>
                  <input type="text" class="input is-small kanban-edit" style="display: none"/>
                  <%= link_to kanban_path(kanban), remote: true, method: :delete do %>
                    <i class="far fa-times-circle is-pulled-right"></i>
                  <% end %>
                  <input type="hidden" name="kanban-id" value="<%=kanban.id%>">
                </div>
                <div class="control has-icons-left has-text-right">
                  <div class="select is-small">
                    <select class="search-box">
                      <option value="">全て</option>
                      <option value="1">チェック済み</option>
                      <option value="0">未チェック</option>
                    </select>
                    <span class="icon is-left">
                      <i class="fas fa-search"></i>
                    </span>
                  </div>
                </div>
                <% if kanban.tasks.any? %>
                  <% kanban.tasks.each_with_index do |task, taskIndex| %>
                    <div class="task-row" draggable="true" data-sort="<%=task.sort%>" data-task-id="<%=task.id%>">
                      <div class="card">
                        <i class="complete-flg far fa<% if task.complete_flg %>-check<%end%>-square is-pulled-right"></i>
                        <span class="task-name"><%= task.name %></span>
                        <input type="text" class="input is-small task-edit" style="display: none"/>
                        <%= link_to task_path(task), remote: true, method: :delete do %>
                          <i class="far fa-times-circle is-pulled-right"></i>
                        <% end %>
                        <input type="hidden" name="task-id" value="<%=task.id%>">
                      </div>
                    </div>
                  <% end %>
                <% end %>
                <div class="task-row-dummy task-row" style="padding : 0.25rem;"></div>
                <div class="task-add dot-border-bottom">
                  <span style="color: silver;">タスクを追加する</span>
                  <input type="text" class="input is-small task-add-input" style="display: none"/>
                </div>
              </div>
            </div>
          </div>
        <% end%>
      </div>
    </div>
  <% else %>
    <div class="is-center">
      まずはかんばんを追加しましょう
      <%= render 'form'%>
    </div>
  <% end %>
</div>